## NumPy - Numerical Python

Advantage of Numpy Array:
  1. Allow Several Mathematical Operations
  2. Faster Operations
  

In [1]:
import numpy as np

### List vs Numpy List - Time Taken

In [2]:
from time import process_time

Time Taken By the List


In [28]:
python_list=[i for i in range(10000000)]
start_time=process_time()

python_list=[i+5 for i in range(10000000)]

end_time=process_time()

print("Total Time of Python List Taken : ",end_time-start_time)


Total Time of Python List Taken :  1.4399187540000007


In [31]:
np_array=np.array([i for i in range(10000000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print("Total Time of Numpy List Taken : ",end_time-start_time)

Total Time of Numpy List Taken :  0.009923405999998636


## Numpy Arrays


In [32]:
list1 = [1,3,5,7]
print(list1)
type(list1)

[1, 3, 5, 7]


list

In [34]:
np_array=np.array([1,3,5,7])
print(np_array)
type(np_array)

[1 3 5 7]


numpy.ndarray

In [35]:
# createing a 1 dimention array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [36]:
a.shape

(5,)

In [37]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
b.shape

(2, 4)

In [41]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholder in numpy array


In [46]:
# create a numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [47]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [50]:
# create an identity matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [51]:
# create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.17206908 0.51738344 0.20653023 0.01182513]
 [0.75608891 0.32160479 0.01598659 0.70813421]
 [0.02673095 0.00896662 0.22152671 0.13576499]]


In [52]:
c= np.random.randint(10,100,(3,5))
print(c)

[[12 16 61 96 89]
 [24 12 98 57 45]
 [45 95 33 88 80]]


In [53]:
# array of evernly space value

d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [54]:
e=np.arange(10,30,5)
print(e)
#

[10 15 20 25]


In [55]:
# convert a list to numpy array
list2=[10,20,30,40,50]
np_array=np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

## Analyzing Numpy Array

In [56]:
c=np.random.randint(10,90,(5,5))
print(c)

[[11 23 54 84 54]
 [20 61 85 15 78]
 [84 41 75 29 11]
 [87 19 52 27 33]
 [80 55 72 50 60]]


In [57]:
# array dimension

print(c.shape)

(5, 5)


In [58]:
# numver of dimenstion
print(c.ndim)

2


In [59]:
print(c.size)

25


In [62]:
#chaking data type of array
print(c.dtype)

int64


## Mathematical Operation in Numpy Array


In [63]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [64]:
a= np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 2 7]
 [8 1 8]
 [9 1 8]]
[[16 11 11]
 [16 17 19]
 [17 10 17]]


In [65]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 13 18]
 [24 18 27]
 [26 11 25]]
[[-14  -9  -4]
 [ -8 -16 -11]
 [ -8  -9  -9]]
[[ 32  22  77]
 [128  17 152]
 [153  10 136]]
[[0.125      0.18181818 0.63636364]
 [0.5        0.05882353 0.42105263]
 [0.52941176 0.1        0.47058824]]


## Array Manipulation

In [66]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 3 3]
 [1 0 6]]
(2, 3)


In [67]:
# transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[7 1]
 [3 0]
 [3 6]]
(3, 2)


In [68]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 5 6]
 [3 4 9]]
(2, 3)


In [72]:
b=a.reshape(2,3)
print(b)
print(b.shape)

[[8 5 6]
 [3 4 9]]
(2, 3)
